# Artifacts need to be set in Platform\.pipelines\.templates\pipeline.artifacts.yml to be used for moduleName and moduleVersion.

parameters:
  vmImage: $(vmImage)
  poolName: $(poolName)
  serviceConnection: '$(serviceConnection)'
  environment: ''
  whatif: false

jobs:
  # Resource Group
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_ResourceGroup
      displayName: 'Deploy ResourceGroup'
      moduleName: '$(RGModuleName)'
      moduleVersion: '$(RGModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true

  # Key Vault
  # ---------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_Key_Vault
      displayName: 'Deploy Key Vault'
      moduleName: '$(KVModuleName)'
      moduleVersion: '$(KVModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/keyVaults/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_ResourceGroup

  # Virtual Machines (Windows) for prfx-NonProd-WindowsPool-001
  # --------------------------------------------------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_Virtual_Machines_Windows
      displayName: 'Deploy Virtual Machines'
      moduleName: '$(VMModuleName)'
      moduleVersion: '$(VMModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/virtualMachines/vmadoaewin001.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_Key_Vault

  # Virtual Machines (Windows) for prfx-NonProd-WindowsPool-001
  # --------------------------------------------------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_Virtual_Machines_Windows_2
      displayName: 'Deploy Virtual Machines'
      moduleName: '$(VMModuleName)'
      moduleVersion: '$(VMModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/virtualMachines/vmadoaewin002.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_Key_Vault

  # Virtual Machines (Windows) for prfx-Prod-WindowsPool-001
  # -----------------------------------------------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_Virtual_Machines_Windows_3
      displayName: 'Deploy Virtual Machines'
      moduleName: '$(VMModuleName)'
      moduleVersion: '$(VMModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/virtualMachines/vmadoaewin003.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_Key_Vault

  # Virtual Machines (Windows) for prfx-Prod-WindowsPool-001
  # -----------------------------------------------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_Virtual_Machines_Windows_4
      displayName: 'Deploy Virtual Machines'
      moduleName: '$(VMModuleName)'
      moduleVersion: '$(VMModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/virtualMachines/vmadoaewin004.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_Key_Vault

  # Deploy Private Endpoint
  # -----------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_PE
      displayName: 'Deploy Private Endpoints'
      moduleName: '$(PEModuleName)'
      moduleVersion: '$(PEModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/privateEndpoints/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
        - Deploy_Virtual_Machines_Windows
        - Deploy_Virtual_Machines_Windows_2
        - Deploy_Virtual_Machines_Windows_3
        - Deploy_Virtual_Machines_Windows_4
