parameters:
  vmImage: $(vmImage)
  poolName: $(poolName)
  serviceConnection: '$(serviceConnection)'
  environment: ''
  whatif: false

jobs:
  # Resource Group
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_ResourceGroup
      displayName: 'Deploy Resource Group'
      moduleName: '$(RGModuleName)'
      moduleVersion: '$(RGModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true

  # Network Watcher EastUS
  # ----------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_NetworkWatcher_EastUS
      displayName: 'Deploy Network Watcher EastUS'
      moduleName: '$(NetworkWatcherModuleName)'
      moduleVersion: '$(NetworkWatcherModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/networkWatchers/prfx-mgmt-ae-nw.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_ResourceGroup

  # Network Watcher WestUS
  # ----------------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_NetworkWatcher_WestUS
      displayName: 'Deploy Network Watcher WestUS'
      moduleName: '$(NetworkWatcherModuleName)'
      moduleVersion: '$(NetworkWatcherModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/networkWatchers/prfx-mgmt-wus-nw.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_ResourceGroup
