name: $(resourceGroupName)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - root/prfx-connectivity-ae-01 (eda24dea-c2b6-4339-b351-21fd78577b4c)/prfx-conn-nw-rg/*

variables:
  - template: pipeline.variables.yml
  - template: /.pipelines/.templates/pipeline.artifacts.yml

stages:
  - stage: Plan
    jobs:
      - template: ./pipeline.jobs.yml
        parameters:
          vmImage: '$(vmImage)'
          poolName: '$(poolName)'
          serviceConnection: '$(serviceConnection)'
          resourceGroupName: '$(resourceGroupName)'
          parameterFilePath: ''
          environment: CONN
          whatif: true
  - stage: Deployment
    jobs:
      - template: ./pipeline.jobs.yml
        parameters:
          vmImage: '$(vmImage)'
          poolName: '$(poolName)'
          serviceConnection: '$(serviceConnection)'
          resourceGroupName: '$(resourceGroupName)'
          parameterFilePath: ''
          environment: CONN
          whatif: false
