# Artifacts need to be set in Platform\.pipelines\.templates\pipeline.artifacts.yml to be used for moduleName and moduleVersion.

parameters:
  vmImage: $(vmImage)
  poolName: $(poolName)
  serviceConnection: '$(serviceConnection)'
  environment: ''
  whatif: false

jobs:
  # Resource Group
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_ResourceGroup
      displayName: 'Deploy ResourceGroup'
      moduleName: '$(RGModuleName)'
      moduleVersion: '$(RGModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true

  # Service Health Action Group
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_ServiceHealthActionGroup
      displayName: 'Create Action Group'
      moduleName: '$(ActionGroupModuleName)'
      moduleVersion: '$(ActionGroupModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/actionGroups/servicehealthag.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
        - Deploy_ResourceGroup

  # Alert Action Group
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_MonitoringActionGroup
      displayName: 'Create Action Group for monitoring alerts'
      moduleName: '$(ActionGroupModuleName)'
      moduleVersion: '$(ActionGroupModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/actionGroups/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Deploy_ResourceGroup

  # Log Analytics workspace
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_LogAnalytics
      displayName: 'Deploy Log Analytics Workspace'
      moduleName: '$(LogAnalyticsModuleName)'
      moduleVersion: '$(LogAnalyticsModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/logAnalytics/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
            - Deploy_ResourceGroup

  # Deploy Private Link Scopes
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_PLS
      displayName: 'Deploy Private Link Scopes'
      moduleName: '$(PrivatelinkScopeModuleName)'
      moduleVersion: '$(PrivatelinkScopeModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/privatelinkscopes/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
        - Deploy_LogAnalytics

  # Deploy Private Endpoints
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_PE
      displayName: 'Deploy Private Endpoints'
      moduleName: '$(PEModuleName)'
      moduleVersion: '$(PEModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/PrivateEndpoints/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
        - Deploy_PLS

  # Deploy Service Health Alerts
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_Alerts
      displayName: 'Deploy Service Health Alerts'
      moduleName: '$(ActivitylogalertModuleName)'
      moduleVersion: '$(ActivitylogalertModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/ServiceHealthAlerts/ServiceHealth.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
        - Create_ServiceHealthActionGroup

  # Deploy Planned Maintenance Alerts
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_PM_Alerts
      displayName: 'Deploy Planned Maintenance Alerts'
      moduleName: '$(ActivitylogalertModuleName)'
      moduleVersion: '$(ActivitylogalertModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/ServiceHealthAlerts/PlannedMaintenance.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: false
      dependsOn:
        - Create_ServiceHealthActionGroup

  # Matrix alert for heart beat
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_HeartBeatAlert
      displayName: 'Create matrix alert for heartbeat'
      moduleName: '$(MetricAlertModuleName)'
      moduleVersion: '$(MetricAlertModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/metricAlerts/heartbeat-alert.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup

  # Alert for 5 GB low disk space
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_5GBLowDiskSpaceAlert
      displayName: 'Create schedule query alert for 5 GB low disk space'
      moduleName: '$(ScheduledQueryModuleName)'
      moduleVersion: '$(ScheduledQueryModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/scheduledQueryRules/5gblowdiskspace.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup

  # Alert for 10 GB low disk space
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_10GBLowDiskSpaceAlert
      displayName: 'Create schedule query alert for 10 GB low disk space'
      moduleName: '$(ScheduledQueryModuleName)'
      moduleVersion: '$(ScheduledQueryModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/scheduledQueryRules/10gblowdiskspace.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup

  # Alert for Cpu processing time
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_CpuProcessingAlert
      displayName: 'Create schedule query alert for high cpu utilization'
      moduleName: '$(ScheduledQueryModuleName)'
      moduleVersion: '$(ScheduledQueryModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/scheduledQueryRules/cpumonitor.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup

  # Alert for disk latency too high
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_HighDiskLatencyAlert
      displayName: 'Create schedule query alert for high disk latency'
      moduleName: '$(ScheduledQueryModuleName)'
      moduleVersion: '$(ScheduledQueryModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/scheduledQueryRules/disklatencytoohigh.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup

  # Alert for memory page too high
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_MemoryPageTooHighAlert
      displayName: 'Create schedule query alert for memory page too high'
      moduleName: '$(ScheduledQueryModuleName)'
      moduleVersion: '$(ScheduledQueryModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/scheduledQueryRules/memorypagespstoohigh.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup

  # Alert for vms down
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Create_UcServerDownAlert
      displayName: 'Create schedule query alert for vms down'
      moduleName: '$(ScheduledQueryModuleName)'
      moduleVersion: '$(ScheduledQueryModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/scheduledQueryRules/vmdown.parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
            - Create_MonitoringActionGroup
