parameters:
      vmImage: $(vmImage)
      poolName: $(poolName)
      serviceConnection: '$(serviceConnection)'
      environment: ''
      whatif: false

jobs:
      # Resource Group
      # --------------
      - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
        parameters:
              jobName: Deploy_ResourceGroup
              displayName: 'Deploy ResourceGroup'
              moduleName: '$(RGModuleName)'
              moduleVersion: '$(RGModuleVersion)'
              parameterFilePath: '${{ parameters.resourceGroupName }}/parameters.json'
              vmImage: '${{ parameters.vmImage }}'
              poolName: '${{ parameters.poolName }}'
              serviceConnection: '${{ parameters.serviceConnection }}'
              environment: '${{ parameters.environment }}'
              whatif: '${{ parameters.whatif }}'
              enabled: true

      # Log Analytics workspace
      # --------------
      - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
        parameters:
              jobName: Deploy_LogAnalytics
              displayName: 'Deploy Log Analytics Workspace'
              moduleName: '$(LogAnalyticsModuleName)'
              moduleVersion: '$(LogAnalyticsModuleVersion)'
              parameterFilePath: '${{ parameters.resourceGroupName }}/logAnalytics/parameters.json'
              vmImage: '${{ parameters.vmImage }}'
              poolName: '${{ parameters.poolName }}'
              serviceConnection: '${{ parameters.serviceConnection }}'
              environment: '${{ parameters.environment }}'
              whatif: '${{ parameters.whatif }}'
              enabled: true
              dependsOn:
                    - Deploy_ResourceGroup
