name: $(resourceGroupName)

parameters:
- name: modulesRepository
  type: string
  default: Azure/ResourceModules
- name: ref
  type: string
  default: main
- name: type
  type: string
  default: github
  values:
  - github
  - git
- name: endpoints
  type: string
  default: segraef

pr: none

trigger:
  batch: true
  branches:
    include:
      - pipelineorchestrated
  # paths:
  #   include:
  #     - root (b3b845c6-2a30-6f4c-62d3-a8b417cb9173)/prfx-connectivity-ae (3e51c849-d082-4b01-9385-455f253a5729)/prfx-conn-ae-network-hub-rg/*

variables:
  - template: /global.variables.yml
  - template: pipeline.variables.yml

resources:
  repositories:
  - repository: modules
    name: $(modulesRepository)
    ref: $(ref)
    endpoint: segraef
    type: github

stages:
  - stage: deployment
    displayName: Deployment
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: rg
          modulePath: '/modules/Microsoft.Resources/resourceGroups/'
          moduleTestFilePath: '$(resourceGroupName)/parameters.json'
          checkoutRepositories:
            - modules
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: rg2
          modulePath: '/modules/Microsoft.Resources/resourceGroups/'
          moduleTestFilePath: '$(resourceGroupName)/parameters.json'
          checkoutRepositories:
            - modules
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: rg3
          modulePath: '/modules/Microsoft.Resources/resourceGroups/'
          moduleTestFilePath: '$(resourceGroupName)/parameters.json'
          checkoutRepositories:
            - modules
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: rg4
          modulePath: '/modules/Microsoft.Resources/resourceGroups/'
          moduleTestFilePath: '$(resourceGroupName)/parameters.json'
          checkoutRepositories:
            - modules
