name: $(resourceGroupName)

pr: none

trigger:
  batch: true
  branches:
    include:
      - pipelineorchestrated
  paths:
    include:
      - root (b3b845c6-2a30-6f4c-62d3-a8b417cb9173)/prfx-connectivity-ae (3e51c849-d082-4b01-9385-455f253a5729)/prfx-conn-ae-network-hub-rg/*

variables:
  - template: pipeline.variables.yml
  - template: '/global.variables.yml'
  # - template: /.pipelines/.templates/pipeline.artifacts.yml
  - group: 'PLATFORM_VARIABLES'

resources:
  repositories:
  - repository: modules
    name: Azure/ResourceModules
    endpoint: segraef
    type: github
    ref: 'refs/heads/main'

stages:
  - stage: test
    jobs:
      - job:
        # uses:
        #   repositories:
        #     - modules
        steps:
          - checkout: github://Azure/ResourceModules
          - pwsh: dir $(Build.SourcesDirectory)
          - pwsh: dir $(Agent.BuildDirectory)
          - pwsh: dir $(System.DefaultWorkingDirectory)
#   - stage: deployment
#     displayName: Deployment
#     jobs:
#       - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
#         uses:
#         parameters:
#           templateFilePath: './modules/Microsoft.Resources/resourceGroups/deploy.bicep'
#           parameterFilePath: '$(resourceGroupName)/parameters.json'
#           location: '$(location)'
#           resourceGroupName: '$(resourceGroupName)'
#           subscriptionId: '$(subscriptionId)'
#           managementGroupId: '$(managementGroupId)'
#           removeDeployment: $(removeDeployment)