name: 'prfx-conn-ae-network-hub-rg (Bicep Registry)'

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - root (b3b845c6-2a30-6f4c-62d3-a8b417cb9173)/prfx-connectivity-ae (3e51c849-d082-4b01-9385-455f253a5729)/prfx-conn-ae-network-hub-rg/*

variables:
  - template: /global.variables.yml
  - template: pipeline.variables.yml

stages:
  - stage:
    displayName: WhatIf
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solution.deploy.yml
        parameters:
          jobName: bicep
          displayName: 'Bicep Deployment'
          modulePath: '$(resourceGroupName)/deploy.br.bicep'
          moduleTestFilePath: '$(resourceGroupName)/parameters.json'
          whatif: true

  - stage:
    displayName: Deploy
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solution.deploy.yml
        parameters:
          jobName: bicep
          displayName: 'Bicep Deployment'
          modulePath: '$(resourceGroupName)/deploy.br.bicep'
          moduleTestFilePath: '$(resourceGroupName)/parameters.json'
