# Artifacts need to be set in Platform\.pipelines\.templates\pipeline.artifacts.yml to be used for moduleName and moduleVersion.

parameters:
  vmImage: $(vmImage)
  poolName: $(poolName)
  serviceConnection: '$(serviceConnection)'
  environment: ''
  whatif: false

jobs:
  # Resource Group
  # --------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_ResourceGroup
      displayName: 'Deploy ResourceGroup'
      moduleName: '$(RGModuleName)'
      moduleVersion: '$(RGModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true

  # Recovery Service Vault
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_RSV
      displayName: 'Deploy Recovery Service Vault'
      moduleName: '$(RSVModuleName)'
      moduleVersion: '$(RSVModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/recoveryServiceVaults/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_ResourceGroup

  # RoleAssignment
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_RoleAssignment
      displayName: 'Deploy RoleAssignment'
      moduleName: '$(RBACModuleName)'
      moduleVersion: '$(RBACModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/roleassignment/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_RSV

  # Private Endpoints
  # ----------------
  - template: /.pipelines/.templates/pipeline.jobs.artifact.deploy.yml
    parameters:
      jobName: Deploy_PE
      displayName: 'Deploy Private Endpoints'
      moduleName: '$(PEModuleName)'
      moduleVersion: '$(PEModuleVersion)'
      parameterFilePath: '${{ parameters.resourceGroupName }}/privateEndpoints/parameters.json'
      vmImage: '${{ parameters.vmImage }}'
      poolName: '${{ parameters.poolName }}'
      serviceConnection: '${{ parameters.serviceConnection }}'
      environment: '${{ parameters.environment }}'
      whatif: '${{ parameters.whatif }}'
      enabled: true
      dependsOn:
        - Deploy_RoleAssignment
        
